cormorack/yodapy

- appveyor.yml
- setup.py
This PR allows the markdown to render for pypi description.
> Allow usage of markdown in desription.

- tests/test_yodapy.py
This pull request covers test case for Yodapy search functionality.
> Test case for Yodapy

- .travis.yml
- README.md
> Trying out Code Coverage

- .travis.yml
- requirements-dev.txt
> Update travis yml to clean up

- requirements-dev.txt
- tests/test_ooi.py
- yodapy/datasources/datasource.py
- yodapy/datasources/ooi/helpers.py
- yodapy/datasources/ooi/ooi_m2m.py
This PR updates the json requests. Progressbar has been added when requesting data and turning data in xarray dataset.
> Update data request, added progressbar.

- requirements.txt
- yodapy/datasources/ooi/m2m.py
- yodapy/datasources/ooi/ooi_m2m.py
This PR initializes the development of streaming dataframe for streaming data.
> Initialize streaming dataframe with streamz.

- docs/source/conf.py
- docs/source/index.rst
- docs/source/modules.rst
This PR adds initial doc for OOI datasource.
> Add OOI doc

- appveyor.yml
- ci/install_python.ps1
This PR runs pytest on appveyor.
> Run pytest on appveyor

- .coveragerc
- tests/test_datasources/test_ooi/test_helpers.py
- tests/test_datasources/test_ooi/test_ooi.py
- tests/test_utils.py
- yodapy/datasources/ooi/__init__.py
- yodapy/datasources/ooi/helpers.py
- yodapy/utils/meta.py
This PR Improves the coverage. Some stuff are being ignored.. probably not the most ideal, but I think the tests should be the most critical stuff, not every nitty gritty.
> Improves coverage, ignore some stuff

- yodapy/datasources/ooi/__init__.py
This PR adds stream argument to request data. Additionally, filtering can now use reference designator, not just name of region, site, and instrument.
> Add stream argument to request data

- yodapy/datasources/ooi/__init__.py
This PR fixes the backslash check url that causes errors in windows.
> Fix check url

- .gitignore
- yodapy/datasources/ooi/__init__.py
This PR adds data status check, just run `check_status` function.
> Add data status check

- yodapy/datasources/ooi/__init__.py
- yodapy/datasources/ooi/helpers.py
- yodapy/utils/parser.py
This PR adds additional features to the ooi datasource.
1. `filter()` has a node option to specify the node that the instrument is located within the platform
2. `data_availibility` returns a dictionary that contains the actual availability of the instruments
3. helper function `get_midnight` is created.
> Update ooi datasource

- tests/test_datasources/test_ooi/test_ooi.py
- yodapy/datasources/ooi/__init__.py
`filter` is a built-in function and it was a bad practice to use `filter` as a function within yodapy, so I am changing this to `search`
> Change function filter to search

- yodapy/datasources/ooi/__init__.py
Closing client seemed to be a bad idea, reverting!
> Closing client was a bad idea

- requirements.txt
- yodapy/datasources/ooi/__init__.py
- yodapy/datasources/ooi/helpers.py
This PR Optimizes yodapy to be able to request data faster and also cut down on preprocessing during merge of xarray dataset from opendap urls.
> Optimize yodapy

- yodapy/datasources/ooi/__init__.py
- yodapy/datasources/ooi/helpers.py
- yodapy/datasources/ooi/m2m_client.py
This parallelize `open_mfdataset`.
> parallelize open_mfdataset rather than concurrent

- yodapy/datasources/ooi/__init__.py
- yodapy/datasources/ooi/helpers.py
- yodapy/utils/parser.py
This PR adds straight download of the netcdf files.
```python
nclist = ooi.download_ncfiles(folder='/home/lsetiawan/Development_Scratch/notebooks/TESTING/')
```
> Add download functionality

- requirements.txt
- yodapy/datasources/ooi/m2m_client.py
- yodapy/utils/parser.py
This PR adds the creation for parameter index here.
> Add parameter index creation with progressbar

- yodapy/datasources/ooi/__init__.py
- yodapy/datasources/ooi/helpers.py
- yodapy/datasources/ooi/m2m_client.py
- yodapy/utils/parser.py
This PR adds the ability to get data from cloud copy. However, it's not stable right now due to no stable copy is available. Additionally, this doesn't not have any date checking yet.
> Adds ability to get data from cloud copy

- .travis.yml
This PR adds OOI_USERNAME and OOI_TOKEN variables.
> Update travis to add OOI Credentials

- tests/test_datasources/test_ooi/test_helpers.py
- tests/test_datasources/test_ooi/test_ooi.py
This PR adds test cases with credentials support for OOI.
> Update test cases

- yodapy/datasources/ooi/__init__.py
- yodapy/datasources/ooi/helpers.py
- yodapy/utils/parser.py
This PR updates the URL for the cloud copy thredds, and change some logic in getting the correct netCDF files.
> Update cloud source

- .coveragerc
- tests/test_datasources/test_ooi/test_ooi.py
Additional test case to check netcdf urls filtering based on start and end date.
> Added test case to filter ncurls

- .travis.yml
- tests/test_datasources/test_ooi/test_ooi.py
- yodapy/datasources/ooi/helpers.py
- yodapy/utils/parser.py
This PR update the retrieval of data from cloud copy!
> Update the filtering of time for cloud copy

- yodapy/datasources/ooi/infrastructure/instruments.csv
This PR updates the metadata preffered stream for `CE04OSPS-SF01B-4F-PCO2WA102`
> Update prefered stream, the current one doesn't exist

- yodapy/datasources/ooi/__init__.py
This PR is a replacement for #84. From @pshivraj suggestions.
> Closes all figures before creation to clear remnants

- tests/test_datasources/test_ooi/test_ooi.py
This Pull request adds data sanity check test function for checking exact similar data values from OOI and Cloud copy.
> Added test case for data sanity check

- tests/test_datasources/test_ooi/test_ooi.py
This PR adds programmatic way to check-data sanity doing away with fix date values and rather using random initialization of date variables and look back window.
> Added random data-sanity check variable definition

- MANIFEST.in
- requirements-dev.txt
- setup.py
- yodapy/datasources/ooi/OOI.py
- yodapy/utils/conn.py
Update setup.py and manifest.in
> Update setup.py and manifest

- yodapy/datasources/ooi/OOI.py
- yodapy/utils/conn.py
Catches 500 and other errors when requesting data, ensures that request data is finished.
> Catch 500 Errors and ensure that queues are done

- yodapy/datasources/ooi/OOI.py
This PR updates the checking of pandas dataframe by using `isinstance` rather than `not` only. 
Closes #99
> Fix sites and regions attributes

- yodapy/datasources/ooi/OOI.py
- yodapy/utils/parser.py
This PR disables the insecure https warning and pandas copy warning that user get when first initializing OOI Object.
> Disable insecure https warning and pandas

- yodapy/datasources/ooi/OOI.py
- yodapy/datasources/ooi/helpers.py
- yodapy/utils/parser.py
This PR adds message to `.instruments` call while threads are loading to fetch the metadata from Uframe.
> Add fetch message while threads are loading

- .travis.yml
- docs/source/index.rst
- requirements.txt
- tests/test_datasources/test_ooi/test_ooi.py
- yodapy/datasources/ooi/OOI.py
This PR adds some text to docs and add functionality for yodapy to be able to access cloud copy of the data.
> Get access to cloud copy and add text to docs

- tests/test_datasources/test_ooi/test_ooi.py
This PR update test to have fixed date.
> Update test to use fixed date

- requirements.txt
- yodapy/datasources/ooi/OOI.py
- yodapy/utils/conn.py
This PR adds functionality to be able to get Bio-acoustic sonar data within the cabled array. It uses [`echopype`](https://github.com/OSOceanAcoustics/echopype) package to process the raw data from the raw data archive.
> Access bao

- yodapy/datasources/ooi/OOI.py
- yodapy/utils/parser.py
This PR adds id attribute to xarray dataset of the sonar data, so user can distinguish between the two datasets.
> Format and add id to sonar data during to_xarray

- yodapy/datasources/ooi/OOI.py
- yodapy/utils/meta.py
This PR adds function to delete all caches in `~/.yodapy/ooi/`.
> Add function to delete all cache

- yodapy/datasources/ooi/infrastructure/cava_sites.csv
This PR adds more sites for CAVA and additional columns.
> Added more sites and cava wp mapping
